### ISSUE TITLE
Documentation needs to explain how to include stylesheet

### ISSUE THREAD

**Issue by suranyami** [lucperkins/bulma-dashboard#2]
Following the `README.md` did not result in a working page layout for me.

I have a Vue.js app with Bulma and Buefy working via `sass-loader` and `node-sass`.

The only way I could get `bulma-dashboard` to work is by visiting the example page at https://lucperkins.github.io/bulma-dashboard/index.html and inspecting the document and copy-pasting the `bulma-dashboard.css` into a local stylesheet in my project.

What would be the correct way to make the stylesheet contained in the NPM package work?

I tried `@import "~/bulma-dashboard.css";` but this did nothing.

**Comment by lucperkins** [comment]
It’s hard to provide pointers without knowing the context. Do you have a public repo?

**Comment by suranyami** [comment]
I can put an example minimal repo up if you like.

My point is, though, if a typical way to use this is `npm install bulma-dashboard` then what is the next step? How is the stylesheet imported? What is the correct path?

Is it assumed to that you've already added `style-loader`/`css-loader` to your NPM project? Coz my out-of-the-box Vue-CLI project only includes `sass-loader` and `node-sass`, so maybe that's an issue?

**Comment by lucperkins** [comment]
Nowadays there are so many build tools and frameworks that you can’t really make any assumptions about how people will use npm packages, and I’m not a front-end dev so I’m honestly not even sure how people typically do things. So there isn’t really much general guidance I can provide.

**Comment by suranyami** [comment]
Yeah, I get that. Maybe just start with how you did it?

I get that the JS ecosystem is a dumpster-fire, but one example is better than none?

BTW: Thanks for this library. It's exactly what I need to help convince people to come over to using Bulma from Bootstrap, coz it almost perfectly matches our current dashboard layout.

**Comment by suranyami** [comment]
Also, where does the `assets/example.html` file live? Might be useful to include that in this repo?

**Comment by suranyami** [comment]
I'll see if I can put together a Webpack example that will work...
