### ISSUE TITLE
Instructions for installing with javascript directly

### ISSUE THREAD

**Issue by lancecarlson** [lucperkins/bulma-dashboard#3]
I npm installed bulma-dashboard and then tried to use the classes and nothing changed. I'm using webpacker / javascript integration, so I import 'bulma' directly into my js. I tried import 'bulma-dashboard' but it couldn't find that. How are you supposed to import this using js or is not possible?

**Comment by lucperkins** [comment]
It's in the `node_modules` directory. The main Sass file is `node_modules/bulma-dashboard/src/bulma-dashboard.sass`. If your pipeline isn't set up to use Sass then you can import one of the CSS files in the `node_modules/bulma-dashboard/dist`.

**Comment by lancecarlson** [comment]
Ah I got it to work. Thanks!
