### ISSUE TITLE
bulma-dashboard.min.css

### ISSUE THREAD

**Issue by MartijnHarmenzon** [lucperkins/bulma-dashboard#5]
When trying the example dashboard provided in the docs folder, the layout was not as showed by your example page. For example, the scroll bars were missing and the sidebars were not filling the entire page. It turned out that the bulma-dashboard.min.css provided in the dist folder is different from the one provided in the docs folder. Can you please inform me why there is a diference?

**Comment by lucperkins** [comment]
@MartijnHarmenzon I just forgot to re-generate the CSS. Should be fixed now.
